### ISSUE TITLE
Failed to initialize Linkam SDK

### ISSUE THREAD

**Issue by GiuseppeCogoni** [swinburne-sensing/pylinkam#2]
Hello,

Thank you for developing this great package!

I recently purchased a license for the Linkam SDK, installed, registered and received the license file from the vendor. 
I installed the pylinkam module via pip (v1.2.6) and copied the **LinkamSDK.dll** file from the *.\SDK\bin\VS2019\Release\x64* folder as well as the **Linkam.lsk** license file received from the vendor into the *.\Lib\site-packages\pylinkam* module.
However, when I try to run the context manager example or the manual example provided in the README, I get an error and within the log file it mentions to register the computer with Linkam Scientific instruments, even though the SDK has been successfully registered.

Is there any step I'm missing in the SDK deployment process?

At the moment I'm utilizing a T96 System Controller (via USB) on a Win10 PC and using python 3.11.7.

P.S.: It turned out the issue was the license file provided by the vendor, upon replacing it with a new one the repository worked fine.

**Comment by ravngr** [comment]
Hey. Sorry, missed this originally but got notified of the close. I've had all sorts of license issues that are non-trivial to impossible to diagnose, we had to go through several iterations to get a working file from the vendor. Glad you got it sorted.
